export const GENERIC = {
  interval: 5000,
  httpCode200: 200,
  httpCode201: 201,
  httpCode400: 400,
  httpCode401: 401,
  httpCode404: 404,
  httpCode500: 500,
  foundToolInfo: 'Below is a list of registered toolss',
  notFoundToolInfo: 'The requested tool could not be found',
  notFoundToolMessage: 'No tools found',
  taskCompleted: 'Task completed successfully',
  titleHref: 'Open website in a new tab:',
  dot: '.',
  emptyString: '',
  errorNetwork: 'no-network-error',
  hyphen: '-',
  installing: 'installing',
  itemsIsNotAnArray: 'The items referring to the tools are in invalid format',
  itemsAreNotDataCLI: 'Items referring to CLI data are in invalid format',
  itemsAreNotSocialNetworks: 'Items are not valid for social networks',
  requiredFieldError: 'required',
  ellipsis: '...',
  slash: '/',
  snake: '_',
  startNumber: 0,
  textFormat: 'text',
  waitForInstallation: 'Wait for the tool to install ...',
  itemUndefined: undefined,
  itemNull: null,
  emptyObject: {},
  emptyArray: [],
  localhostAPI: process.env.REACT_APP_BASE_URL_API,
  localhostWeb: process.env.REACT_APP_BASE_URL_WEB,
  noSitesToDisplay: 'No sites to display'
};
