#!/usr/bin/env bash
# shellcheck disable=2155
# vim: et ts=2 sw=2 ft=sh:

getData() {
  cd ${pwdCLI}

  local dataJSON="require('./data.json')"

  # Checks whether the parameter was passed
  if [ "$#" -ne 1 ]; then
    throw_new_error "The requested data could not be obtained!" "info"
  fi

  # Returns the requested data
  node -pe ${dataJSON}.${@}
}