#!/usr/bin/env bash
# shellcheck disable=2155
# vim: et ts=2 sw=2 ft=sh:

makeFlutter() {
  active="false"
  avatarURL="flutter"
  avatarURLSTR=${avatarURL// /'__'}

  name="flutter"
  nameSTR=${name// /'__'}

  info="Flutter is Google UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase."
  infoSTR=${info// /'__'}

  site="https://flutter.dev/"
  siteSTR=${site// /'__'}

  status=${NOT_FOUND}
  version=""

  if ( flutter --version > /dev/null 2>&1 ); then
    active="true"
    status=${INSTALLED}
    version=$(flutter --version 2>&1 | head -n 1)
  fi

  statusSTR=${status// /'__'}
  versionSTR=${version// /'__'}

  query="active=${active}&avatarURL=${avatarURLSTR}&name=${nameSTR}&info=${infoSTR}&site=${siteSTR}&status=${statusSTR}&version=${versionSTR}"

  requestHTTPAddNewTool ${query}
}