#!/usr/bin/env bash
# shellcheck disable=2155
# vim: et ts=2 sw=2 ft=sh:

makeIonic() {
  active="false"
  avatarURL="ionic"
  avatarURLSTR=${avatarURL// /'__'}

  name="ionic"
  nameSTR=${name// /'__'}

  info="An open source mobile UI toolkit for building high quality, cross-platform native and web app experiences."
  infoSTR=${info// /'__'}

  site="https://ionicframework.com/"
  siteSTR=${site// /'__'}

  status=${NOT_FOUND}
  version=""

  if ( ionic --version > /dev/null 2>&1 ); then
    active="true"
    status=${INSTALLED}
    version=$(ionic --version 2>&1 | head -n 1)
  fi

  statusSTR=${status// /'__'}
  versionSTR=${version// /'__'}

  query="active=${active}&avatarURL=${avatarURLSTR}&name=${nameSTR}&info=${infoSTR}&site=${siteSTR}&status=${statusSTR}&version=${versionSTR}"

  requestHTTPAddNewTool ${query}
}