export const CONSTANTS = {
  interval: 5000,
  httpCode200: 200,
  httpCode201: 201,
  httpCode400: 400,
  httpCode401: 401,
  httpCode404: 404,
  httpCode500: 500,
  foundToolInfo: 'Below is a list of registered tools',
  notFoundDataCLIInfo: 'CLI configuration data not found',
  notFoundDataCLIMessage: 'CLI data not found',
  notFoundSocialNetworkInfo: 'Social Network not found',
  notFoundSocialNetworkMessage: 'Could not find social network',
  notFoundToolInfo: 'The requested tool could not be found',
  notFoundToolMessage: 'No tools found',
  taskCompleted: 'Task completed successfully',
  dot: '.',
  emptyString: '',
  errorNetwork: 'no-network-error',
  hyphen: '-',
  installing: 'installing',
  itemsIsNotAnArray: 'The items referring to the tools are in invalid format',
  requiredFieldError: 'required',
  slash: '/',
  snake: '_',
  textFormat: 'text',
  waitForInstallation: 'Wait for the tool to install ...',
  itemUndefined: undefined,
  itemNull: null,
  emptyObject: {},
  emptyArray: [],
  snakeCaseRegex: /(.*?)_([a-zA-Z])/,
  pathImages: 'src/assets/images',
  defaultAvatar: 'default-avatar',
};
